### ISSUE TITLE
Default to notepad on windows

### ISSUE THREAD

**Issue by yajo** [rec/editor#2]
I've been testing this on a Windows VM as I want it for a CLI app that supports it.

I think it's not so common that Windows has vim, but notepad is always there. How about using notepad as default editor there?

**Comment by rec** [comment]
Such a good idea!

I just got up moments ago.  Send me the string you think is reasonable for this and I'll quickly push a change with that to test.  

Then I'll have breakfast and look at your pull request, unless the pull request is needed to make the change, in which case it might have to wait until after foods.

**Comment by yajo** [comment]
Just 'notepad' is enough, although I think you already figured that out... 😁Enviado de Samsung Mobile
-------- Mensaje original --------De: Tom Swirly <notifications@github.com> Fecha: 19/9/20  8:11  (GMT+01:00) Para: rec/editor <editor@noreply.github.com> Cc: Jairo Llopis <yajo.sk8@gmail.com>, Author <author@noreply.github.com> Asunto: Re: [rec/editor] Default to notepad on windows? (#2) 
Such a good idea!
I just got up moments ago.  Send me the string you think is reasonable for this and I'll quickly push a change with that to test.
Then I'll have breakfast and look at your pull request, unless the pull request is needed to make the change, in which case it might have to wait until after foods.
