### ISSUE TITLE
Opening an editor on windows raises a PermissionError

### ISSUE THREAD

**Issue by yajo** [rec/editor#4]
I'd say that the problem is that `editor` is owning the temp file and, at the same time, tries to open another process owning it. See:

![Peek 19-09-2020 08-08](https://user-images.githubusercontent.com/973709/93660454-61e55000-fa4f-11ea-9ffe-fd69878fd0cf.gif)

**Comment by yajo** [comment]
Oops sorry, that was using inquirer.

This one is using editor directly:

![Peek 19-09-2020 08-10](https://user-images.githubusercontent.com/973709/93660474-9bb65680-fa4f-11ea-9b28-5920b3c967c3.gif)

**Comment by rec** [comment]
Well, this is a clear bug report, but hmm, I don't quite understand what's going on here.

Please bear with me - my knowledge of how Windows Python I/O differs from other systems is small, but I need to know this, as I have other utilities I know don't work.

Can you send me just the text of the tracebacks, please?

I'm determined to solve this one, if I can!

**Comment by rec** [comment]
No need for the stack trace, I am fairly sure I understand what's going on.

I believe that in Windows, you can't open a file you already have open.  I think this is even in the Python documentation somewhere.

I can sort this out pretty easily.  I'll come up with a version to test!

**Comment by yajo** [comment]
If it serves you, I also don't use windows personally, but you can get a dev vm for free from windows website.
